### ISSUE TITLE
Error when using Spring Boot & Spring Cloud latest version

### ISSUE THREAD

**Issue by hendisantika** [spring-cloud-samples/feign-eureka#9]
Nice repo.

But, I got error when using Spring Boot (1.5.8) & Spring Cloud latest (Finchley.M2) version.

```
07:18:03.203 [main] DEBUG org.springframework.boot.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/charsets.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/deploy.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/cldrdata.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/dnsns.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jaccess.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jfxrt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/localedata.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/nashorn.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunec.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/zipfs.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/javaws.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jce.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jfr.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jfxswt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jsse.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/management-agent.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/plugin.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/resources.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/rt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/ant-javafx.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/dt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/javafx-mx.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/jconsole.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/packager.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/sa-jdi.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/tools.jar, file:/Users/hendisantika/Documents/IdeaProjects/github/feign-eureka/server/target/classes/, file:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-web/1.5.8.RELEASE/spring-boot-starter-web-1.5.8.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter/1.5.8.RELEASE/spring-boot-starter-1.5.8.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot/1.5.8.RELEASE/spring-boot-1.5.8.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.5.8.RELEASE/spring-boot-autoconfigure-1.5.8.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-logging/1.5.8.RELEASE/spring-boot-starter-logging-1.5.8.RELEASE.jar, file:/Users/hendisantika/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar, file:/Users/hendisantika/.m2/repository/ch/qos/logback/logback-core/1.1.11/logback-core-1.1.11.jar, file:/Users/hendisantika/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar, file:/Users/hendisantika/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar, file:/Users/hendisantika/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.25/log4j-over-slf4j-1.7.25.jar, file:/Users/hendisantika/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar, file:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/1.5.8.RELEASE/spring-boot-starter-tomcat-1.5.8.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.23/tomcat-embed-core-8.5.23.jar, file:/Users/hendisantika/.m2/repository/org/apache/tomcat/tomcat-annotations-api/8.5.23/tomcat-annotations-api-8.5.23.jar, file:/Users/hendisantika/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.23/tomcat-embed-el-8.5.23.jar, file:/Users/hendisantika/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.23/tomcat-embed-websocket-8.5.23.jar, file:/Users/hendisantika/.m2/repository/org/hibernate/hibernate-validator/5.3.5.Final/hibernate-validator-5.3.5.Final.jar, file:/Users/hendisantika/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar, file:/Users/hendisantika/.m2/repository/org/jboss/logging/jboss-logging/3.3.1.Final/jboss-logging-3.3.1.Final.jar, file:/Users/hendisantika/.m2/repository/com/fasterxml/classmate/1.3.4/classmate-1.3.4.jar, file:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.10/jackson-databind-2.8.10.jar, file:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar, file:/Users/hendisantika/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.10/jackson-core-2.8.10.jar, file:/Users/hendisantika/.m2/repository/org/springframework/spring-web/4.3.12.RELEASE/spring-web-4.3.12.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/spring-aop/4.3.12.RELEASE/spring-aop-4.3.12.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/spring-beans/4.3.12.RELEASE/spring-beans-4.3.12.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/spring-context/4.3.12.RELEASE/spring-context-4.3.12.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/spring-webmvc/4.3.12.RELEASE/spring-webmvc-4.3.12.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/spring-expression/4.3.12.RELEASE/spring-expression-4.3.12.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/1.5.8.RELEASE/spring-boot-starter-actuator-1.5.8.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/boot/spring-boot-actuator/1.5.8.RELEASE/spring-boot-actuator-1.5.8.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter-feign/2.0.0.M2/spring-cloud-starter-feign-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter-openfeign/2.0.0.M2/spring-cloud-starter-openfeign-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter/2.0.0.M2/spring-cloud-starter-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-context/2.0.0.M2/spring-cloud-context-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/org/springframework/security/spring-security-rsa/1.0.5.RELEASE/spring-security-rsa-1.0.5.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.jar, file:/Users/hendisantika/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-netflix-core/2.0.0.M2/spring-cloud-netflix-core-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-commons/2.0.0.M2/spring-cloud-commons-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/org/springframework/security/spring-security-crypto/4.2.3.RELEASE/spring-security-crypto-4.2.3.RELEASE.jar, file:/Users/hendisantika/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar, file:/Users/hendisantika/.m2/repository/org/apache/httpcomponents/httpcore/4.4.8/httpcore-4.4.8.jar, file:/Users/hendisantika/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, file:/Users/hendisantika/.m2/repository/io/github/openfeign/feign-core/9.5.0/feign-core-9.5.0.jar, file:/Users/hendisantika/.m2/repository/org/jvnet/animal-sniffer-annotation/1.0/animal-sniffer-annotation-1.0.jar, file:/Users/hendisantika/.m2/repository/io/github/openfeign/feign-slf4j/9.5.0/feign-slf4j-9.5.0.jar, file:/Users/hendisantika/.m2/repository/io/github/openfeign/feign-hystrix/9.5.0/feign-hystrix-9.5.0.jar, file:/Users/hendisantika/.m2/repository/com/netflix/archaius/archaius-core/0.7.5/archaius-core-0.7.5.jar, file:/Users/hendisantika/.m2/repository/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar, file:/Users/hendisantika/.m2/repository/com/netflix/hystrix/hystrix-core/1.5.12/hystrix-core-1.5.12.jar, file:/Users/hendisantika/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter-netflix-ribbon/2.0.0.M2/spring-cloud-starter-netflix-ribbon-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/com/netflix/ribbon/ribbon/2.2.2/ribbon-2.2.2.jar, file:/Users/hendisantika/.m2/repository/com/netflix/ribbon/ribbon-transport/2.2.2/ribbon-transport-2.2.2.jar, file:/Users/hendisantika/.m2/repository/io/reactivex/rxnetty-contexts/0.4.9/rxnetty-contexts-0.4.9.jar, file:/Users/hendisantika/.m2/repository/io/reactivex/rxnetty-servo/0.4.9/rxnetty-servo-0.4.9.jar, file:/Users/hendisantika/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar, file:/Users/hendisantika/.m2/repository/io/reactivex/rxnetty/0.4.9/rxnetty-0.4.9.jar, file:/Users/hendisantika/.m2/repository/io/netty/netty-codec-http/4.0.27.Final/netty-codec-http-4.0.27.Final.jar, file:/Users/hendisantika/.m2/repository/io/netty/netty-codec/4.0.27.Final/netty-codec-4.0.27.Final.jar, file:/Users/hendisantika/.m2/repository/io/netty/netty-handler/4.0.27.Final/netty-handler-4.0.27.Final.jar, file:/Users/hendisantika/.m2/repository/io/netty/netty-transport-native-epoll/4.0.27.Final/netty-transport-native-epoll-4.0.27.Final.jar, file:/Users/hendisantika/.m2/repository/io/netty/netty-common/4.0.27.Final/netty-common-4.0.27.Final.jar, file:/Users/hendisantika/.m2/repository/io/netty/netty-buffer/4.0.27.Final/netty-buffer-4.0.27.Final.jar, file:/Users/hendisantika/.m2/repository/io/netty/netty-transport/4.0.27.Final/netty-transport-4.0.27.Final.jar, file:/Users/hendisantika/.m2/repository/com/netflix/ribbon/ribbon-core/2.2.2/ribbon-core-2.2.2.jar, file:/Users/hendisantika/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar, file:/Users/hendisantika/.m2/repository/com/netflix/ribbon/ribbon-httpclient/2.2.2/ribbon-httpclient-2.2.2.jar, file:/Users/hendisantika/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar, file:/Users/hendisantika/.m2/repository/com/netflix/netflix-commons/netflix-commons-util/0.1.1/netflix-commons-util-0.1.1.jar, file:/Users/hendisantika/.m2/repository/com/netflix/ribbon/ribbon-loadbalancer/2.2.2/ribbon-loadbalancer-2.2.2.jar, file:/Users/hendisantika/.m2/repository/com/netflix/netflix-commons/netflix-statistics/0.1.1/netflix-statistics-0.1.1.jar, file:/Users/hendisantika/.m2/repository/io/reactivex/rxjava/1.1.10/rxjava-1.1.10.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter-netflix-archaius/2.0.0.M2/spring-cloud-starter-netflix-archaius-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/commons-configuration/commons-configuration/1.8/commons-configuration-1.8.jar, file:/Users/hendisantika/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar, file:/Users/hendisantika/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter-eureka/2.0.0.M2/spring-cloud-starter-eureka-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-starter-netflix-eureka-client/2.0.0.M2/spring-cloud-starter-netflix-eureka-client-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/org/springframework/cloud/spring-cloud-netflix-eureka-client/2.0.0.M2/spring-cloud-netflix-eureka-client-2.0.0.M2.jar, file:/Users/hendisantika/.m2/repository/com/netflix/eureka/eureka-client/1.7.0/eureka-client-1.7.0.jar, file:/Users/hendisantika/.m2/repository/org/codehaus/jettison/jettison/1.3.7/jettison-1.3.7.jar, file:/Users/hendisantika/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar, file:/Users/hendisantika/.m2/repository/com/netflix/netflix-commons/netflix-eventbus/0.3.0/netflix-eventbus-0.3.0.jar, file:/Users/hendisantika/.m2/repository/com/netflix/netflix-commons/netflix-infix/0.3.0/netflix-infix-0.3.0.jar, file:/Users/hendisantika/.m2/repository/commons-jxpath/commons-jxpath/1.3/commons-jxpath-1.3.jar, file:/Users/hendisantika/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar, file:/Users/hendisantika/.m2/repository/org/antlr/antlr-runtime/3.4/antlr-runtime-3.4.jar, file:/Users/hendisantika/.m2/repository/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar, file:/Users/hendisantika/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar, file:/Users/hendisantika/.m2/repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar, file:/Users/hendisantika/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.jar, file:/Users/hendisantika/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar, file:/Users/hendisantika/.m2/repository/com/netflix/servo/servo-core/0.10.1/servo-core-0.10.1.jar, file:/Users/hendisantika/.m2/repository/com/netflix/servo/servo-internal/0.10.1/servo-internal-0.10.1.jar, file:/Users/hendisantika/.m2/repository/com/sun/jersey/jersey-core/1.19.1/jersey-core-1.19.1.jar, file:/Users/hendisantika/.m2/repository/com/sun/jersey/jersey-client/1.19.1/jersey-client-1.19.1.jar, file:/Users/hendisantika/.m2/repository/com/sun/jersey/contribs/jersey-apache-client4/1.19.1/jersey-apache-client4-1.19.1.jar, file:/Users/hendisantika/.m2/repository/com/google/inject/guice/4.1.0/guice-4.1.0.jar, file:/Users/hendisantika/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar, file:/Users/hendisantika/.m2/repository/com/netflix/eureka/eureka-core/1.7.0/eureka-core-1.7.0.jar, file:/Users/hendisantika/.m2/repository/org/codehaus/woodstox/woodstox-core-asl/4.4.1/woodstox-core-asl-4.4.1.jar, file:/Users/hendisantika/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar, file:/Users/hendisantika/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar, file:/Users/hendisantika/.m2/repository/com/netflix/ribbon/ribbon-eureka/2.2.2/ribbon-eureka-2.2.2.jar, file:/Users/hendisantika/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.jar, file:/Users/hendisantika/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar, file:/Users/hendisantika/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar, file:/Users/hendisantika/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar, file:/Users/hendisantika/.m2/repository/org/springframework/spring-core/4.3.12.RELEASE/spring-core-4.3.12.RELEASE.jar, file:/Applications/IntelliJ%20IDEA.app/Contents/lib/idea_rt.jar]
07:18:03.206 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Class;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:158)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:99)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:65)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at demo.HelloServerApplication.main(HelloServerApplication.java:29)

Process finished with exit code 1

```

Any suggestion?

Thanks

**Comment by spencergibb** [comment]
Finchley only works with Spring Boot 2

**Comment by hendisantika** [comment]
I created base on your repo / clone : 

But I still got the error.

Could you please run [my Repo](https://github.com/hendisantika/feign-eureka)
